### ISSUE TITLE
Create laravel integration

### ISSUE THREAD

**Issue by sagikazarmark** [dineshrabara/barcode#30]
Hi,

This seems to be an awesome library, however I don't really understand why a laravel package is a dependency. Looking at the code, only the laravel integration part needs it. Would be awesome to move all that to a laravel integration package.

**Comment by tklovett** [comment]
I've got a fork of this library where I've separated out the barcode generation from the Laravel integration.  If you check out the [dev branch](https://github.com/tklovett/barcodes/tree/dev), I've got a [work-in-progress commit](https://github.com/tklovett/barcodes/commit/71ba77fbbde41c25ee18cfbf43b823612c6bdc9c) with my progress so far. I'm also doing a major refactor to separate the logic for each barcode type and reduce code duplication.

**Comment by sagikazarmark** [comment]
@tklovett :+1:

**Comment by dineshrabara** [comment]
Great work @tklovett 

Thanks @tklovett
