### ISSUE TITLE
Call to undefined method Dinesh\Barcode\Facades\DNS1D

### ISSUE THREAD

**Issue by lapiandroid** [dineshrabara/barcode#31]
Hi,
I've this error after installation from composer
[2015-01-26 14:02:22] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Dinesh\Barcode\Facades\DNS1DFacade::getBarcodeHTML().

Example call
DNS1D::getBarcodeHTML("4445", "EAN13");

**Comment by dineshrabara** [comment]
just alias on config file

On 26 January 2015 at 19:38, lapiandroid <notifications@github.com> wrote:

> Hi,
> I've this error after installation from composer
> [2015-01-26 14:02:22] production.ERROR: exception
> 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call
> to undefined method Dinesh\Barcode\Facades\DNS1DFacade::getBarcodeHTML().
>
> Example call
> DNS1D::getBarcodeHTML("4445", "EAN13");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dineshrabara/barcode/issues/31>.
>



-- 
Regards,

*Dinesh Rabara*
*software Developer*
