### ISSUE TITLE
Is there a way to generate png with string?

### ISSUE THREAD

**Issue by raykwok** [dineshrabara/barcode#32]
Is there a way to generate png with string below the barcode?

**Comment by dineshrabara** [comment]
@raykwok  check wiki https://github.com/dineshrabara/barcode/wiki/Barcode-Types

**Comment by raykwok** [comment]
@dineshrabara Hello, what I got is only the barcode picture, I mean that I want to add the extra string to the picture.

**Comment by dineshrabara** [comment]
it's not possible here
