### ISSUE TITLE
laravel 5 compatibilty

### ISSUE THREAD

**Issue by mouhsinelonly** [dineshrabara/barcode#33]
please add laravel 5 support ,

**Comment by tiger2wander** [comment]
:+1:

**Comment by warchildmd** [comment]
see #35 .
Hope Dinesh will merge.

**Comment by raykwok** [comment]
+1

**Comment by kw-pr** [comment]
+1

**Comment by adamgoose** [comment]
It has been implemented to this repository as well. See the `composer.json` @ master. This issue is now a matter of tagging a new release.

**Comment by dineshrabara** [comment]
please check  branch 5.0 and V4.0
