### ISSUE TITLE
Incompatibility with Laravel 4

### ISSUE THREAD

**Issue by leonardob17** [dineshrabara/barcode#40]
I can not update my project with "composer update" because of that error:
http://prntscr.com/6ujdp3

**Comment by illuminate3** [comment]
ugh, me too!

**Comment by dineshrabara** [comment]
please use "dinesh/barcode": "V4.0"

**Comment by leonardob17** [comment]
The problem continues. And the error is the same.

**Comment by leonardob17** [comment]
The suggestion of the @illuminate3 worked. Thanks man!
