### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by wemersonjanuario** [dineshrabara/barcode#47]
Could you generate new version tag for Laravel 5.1 support? Thanks!

**Comment by dineshrabara** [comment]
please check     "dinesh/barcode": "5.0.*@dev"

**Comment by wemersonjanuario** [comment]
this works only if Laravel 5.0.x? I need Laravel 5.1.x
look 
"illuminate/support": "5.0.x"

**Comment by NazarAli** [comment]
i have same problem
what the solution

**Comment by dineshrabara** [comment]
please check https://github.com/dineshrabara/barcode/issues/48

**Comment by wemersonjanuario** [comment]
thanks
